ALTER TABLE FEED_POST ADD COLUMN IF NOT EXISTS ANIMAL_ID BIGINT;

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_ANIMAL ON FEED_POST (ANIMAL_ID);

ALTER TABLE FEED_POST DROP CONSTRAINT IF EXISTS FK_FEED_POST_ANIMAL;

ALTER TABLE FEED_POST
    ADD CONSTRAINT FK_FEED_POST_ANIMAL
    FOREIGN KEY (ANIMAL_ID)
    REFERENCES ANIMAL (ID_ANIMAL);
