CREATE SEQUENCE IF NOT EXISTS SEQ_NOTIFICATION START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    ID_NOTIFICATION BIGINT PRIMARY KEY,
    RECIPIENT_USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(120) NOT NULL,
    MESSAGE VARCHAR(500) NOT NULL,
    TYPE VARCHAR(60) NOT NULL,
    RELATED_ENTITY_TYPE VARCHAR(60),
    RELATED_ENTITY_ID BIGINT,
    ACTION_URL VARCHAR(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    READ_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT FK_NOTIFICATION_RECIPIENT
        FOREIGN KEY (RECIPIENT_USER_ID)
        REFERENCES USERS (ID_USER)
);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_RECIPIENT_CREATED
    ON NOTIFICATION (RECIPIENT_USER_ID, CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_RECIPIENT_UNREAD
    ON NOTIFICATION (RECIPIENT_USER_ID, READ_AT);
