ALTER TABLE USERS
    ADD COLUMN IF NOT EXISTS EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS EMAIL_VERIFICATION_TOKEN_HASH VARCHAR(64),
    ADD COLUMN IF NOT EXISTS EMAIL_VERIFICATION_EXPIRES_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE USERS
    ALTER COLUMN EMAIL_VERIFIED SET DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL_VERIFICATION_TOKEN_HASH
    ON USERS (EMAIL_VERIFICATION_TOKEN_HASH);
