CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ANIMAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ANIMAL_PHOTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REQUEST START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
    ID_USER BIGINT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(120) NOT NULL,
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    REGISTRATION_DATE TIMESTAMP NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    USER_TYPE VARCHAR(30) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID_USER)
);

CREATE TABLE ANIMAL (
    ID_ANIMAL BIGINT NOT NULL,
    ANIMAL_NAME VARCHAR(100) NOT NULL,
    SPECIES VARCHAR(50) NOT NULL,
    BREED VARCHAR(100),
    BIRTH_DATE DATE,
    AGE INTEGER,
    ANIMAL_SIZE VARCHAR(20),
    SEX CHAR(1),
    WEIGHT_KG DECIMAL(5, 2),
    VACCINATED CHAR(1) NOT NULL,
    NEUTERED CHAR(1) NOT NULL,
    DESCRIPTION VARCHAR(500),
    STATUS VARCHAR(20) NOT NULL,
    REGISTRATION_DATE TIMESTAMP NOT NULL,
    FK_USERS_ID_USER BIGINT,
    CONSTRAINT PK_ANIMAL PRIMARY KEY (ID_ANIMAL),
    CONSTRAINT FK_ANIMAL_USER FOREIGN KEY (FK_USERS_ID_USER) REFERENCES USERS (ID_USER)
);

CREATE TABLE ANIMAL_PHOTO (
    ID_PHOTO BIGINT NOT NULL,
    PHOTO_URL VARCHAR(255) NOT NULL,
    IS_MAIN CHAR(1) NOT NULL,
    FK_ANIMAL_ID_ANIMAL BIGINT NOT NULL,
    CONSTRAINT PK_ANIMAL_PHOTO PRIMARY KEY (ID_PHOTO),
    CONSTRAINT FK_ANIMAL_PHOTO_ANIMAL FOREIGN KEY (FK_ANIMAL_ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL)
);

CREATE TABLE ADOPTION_REQUEST (
    ID_REQUEST BIGINT NOT NULL,
    MESSAGE VARCHAR(500),
    STATUS VARCHAR(20) NOT NULL,
    REQUEST_DATE TIMESTAMP NOT NULL,
    RESPONSE_DATE TIMESTAMP,
    FK_ANIMAL_ID_ANIMAL BIGINT NOT NULL,
    FK_USERS_ID_USER BIGINT NOT NULL,
    CONSTRAINT PK_ADOPTION_REQUEST PRIMARY KEY (ID_REQUEST),
    CONSTRAINT FK_ADOPTION_REQUEST_ANIMAL FOREIGN KEY (FK_ANIMAL_ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL),
    CONSTRAINT FK_ADOPTION_REQUEST_USER FOREIGN KEY (FK_USERS_ID_USER) REFERENCES USERS (ID_USER)
);
