ALTER TABLE USERS
    ADD CONSTRAINT UK_USERS_CPF UNIQUE (CPF);

ALTER TABLE USERS
    ADD CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL);

ALTER TABLE USERS
    ADD CONSTRAINT CK_USERS_USER_TYPE
        CHECK (USER_TYPE IN ('COMMON', 'ADMIN'));

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_STATUS
        CHECK (STATUS IN ('AVAILABLE', 'ADOPTED', 'REMOVED'));

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_SEX
        CHECK (SEX IS NULL OR SEX IN ('M', 'F'));

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_VACCINATED
        CHECK (VACCINATED IN ('Y', 'N'));

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_NEUTERED
        CHECK (NEUTERED IN ('Y', 'N'));

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_AGE
        CHECK (AGE IS NULL OR AGE >= 0);

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_WEIGHT
        CHECK (WEIGHT_KG IS NULL OR WEIGHT_KG > 0);

ALTER TABLE ANIMAL_PHOTO
    ADD CONSTRAINT CK_ANIMAL_PHOTO_IS_MAIN
        CHECK (IS_MAIN IN ('Y', 'N'));

ALTER TABLE ADOPTION_REQUEST
    ADD CONSTRAINT CK_ADOPTION_REQUEST_STATUS
        CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'));
