ALTER TABLE ANIMAL
    ADD COLUMN IF NOT EXISTS AGE_VALUE INTEGER;

ALTER TABLE ANIMAL
    ADD COLUMN IF NOT EXISTS AGE_UNIT VARCHAR(20);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'animal'
          AND column_name = 'age'
    ) THEN
        UPDATE ANIMAL
        SET AGE_VALUE = COALESCE(AGE_VALUE, AGE),
            AGE_UNIT = COALESCE(AGE_UNIT, 'YEARS')
        WHERE AGE IS NOT NULL;
    END IF;
END $$;

UPDATE ANIMAL
SET AGE_UNIT = 'YEARS'
WHERE AGE_VALUE IS NOT NULL
  AND AGE_UNIT IS NULL;

ALTER TABLE ANIMAL
    DROP CONSTRAINT IF EXISTS CK_ANIMAL_AGE;

ALTER TABLE ANIMAL
    DROP CONSTRAINT IF EXISTS CK_ANIMAL_AGE_VALUE;

ALTER TABLE ANIMAL
    DROP CONSTRAINT IF EXISTS CK_ANIMAL_AGE_UNIT;

ALTER TABLE ANIMAL
    DROP CONSTRAINT IF EXISTS CK_ANIMAL_AGE_COMPLETE;

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_AGE_VALUE
        CHECK (AGE_VALUE IS NULL OR AGE_VALUE >= 0);

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_AGE_UNIT
        CHECK (AGE_UNIT IS NULL OR AGE_UNIT IN ('MONTHS', 'YEARS'));

ALTER TABLE ANIMAL
    ADD CONSTRAINT CK_ANIMAL_AGE_COMPLETE
        CHECK (
            (AGE_VALUE IS NULL AND AGE_UNIT IS NULL)
            OR (AGE_VALUE IS NOT NULL AND AGE_UNIT IS NOT NULL)
        );

ALTER TABLE ANIMAL
    DROP COLUMN IF EXISTS AGE;
