CREATE SEQUENCE IF NOT EXISTS SEQ_FEED_POST START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS FEED_POST (
    ID_FEED_POST BIGINT NOT NULL DEFAULT nextval('SEQ_FEED_POST'),
    AUTHOR_USER_ID BIGINT NOT NULL,
    ANIMAL_ID BIGINT,
    CONTENT VARCHAR(1000) NOT NULL,
    IMAGE_URL VARCHAR(500),
    POST_TYPE VARCHAR(30) NOT NULL DEFAULT 'GENERAL',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_FEED_POST PRIMARY KEY (ID_FEED_POST),
    CONSTRAINT FK_FEED_POST_AUTHOR FOREIGN KEY (AUTHOR_USER_ID) REFERENCES USERS (ID_USER),
    CONSTRAINT FK_FEED_POST_ANIMAL FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL (ID_ANIMAL),
    CONSTRAINT CK_FEED_POST_TYPE CHECK (POST_TYPE IN ('GENERAL', 'ADOPTION_SUCCESS', 'ANIMAL_UPDATE'))
);

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_CREATED_AT
    ON FEED_POST (CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_AUTHOR
    ON FEED_POST (AUTHOR_USER_ID);

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_ANIMAL
    ON FEED_POST (ANIMAL_ID);
