ALTER TABLE USERS
    ALTER COLUMN REGISTRATION_DATE TYPE TIMESTAMP WITH TIME ZONE
    USING REGISTRATION_DATE AT TIME ZONE 'UTC';

ALTER TABLE ANIMAL
    ALTER COLUMN REGISTRATION_DATE TYPE TIMESTAMP WITH TIME ZONE
    USING REGISTRATION_DATE AT TIME ZONE 'UTC';

ALTER TABLE ADOPTION_REQUEST
    ALTER COLUMN REQUEST_DATE TYPE TIMESTAMP WITH TIME ZONE
    USING REQUEST_DATE AT TIME ZONE 'UTC',
    ALTER COLUMN RESPONSE_DATE TYPE TIMESTAMP WITH TIME ZONE
    USING RESPONSE_DATE AT TIME ZONE 'UTC';

ALTER TABLE FEED_POST
    ALTER COLUMN CREATED_AT TYPE TIMESTAMP WITH TIME ZONE
    USING CREATED_AT AT TIME ZONE 'UTC';
