CREATE SEQUENCE IF NOT EXISTS SEQ_FEED_POST_LIKE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_FEED_POST_COMMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS FEED_POST_LIKE (
    ID_FEED_POST_LIKE BIGINT NOT NULL DEFAULT nextval('SEQ_FEED_POST_LIKE'),
    FEED_POST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_FEED_POST_LIKE PRIMARY KEY (ID_FEED_POST_LIKE),
    CONSTRAINT FK_FEED_POST_LIKE_POST FOREIGN KEY (FEED_POST_ID) REFERENCES FEED_POST (ID_FEED_POST) ON DELETE CASCADE,
    CONSTRAINT FK_FEED_POST_LIKE_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID_USER) ON DELETE CASCADE,
    CONSTRAINT UK_FEED_POST_LIKE_POST_USER UNIQUE (FEED_POST_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS FEED_POST_COMMENT (
    ID_FEED_POST_COMMENT BIGINT NOT NULL DEFAULT nextval('SEQ_FEED_POST_COMMENT'),
    FEED_POST_ID BIGINT NOT NULL,
    AUTHOR_USER_ID BIGINT NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_FEED_POST_COMMENT PRIMARY KEY (ID_FEED_POST_COMMENT),
    CONSTRAINT FK_FEED_POST_COMMENT_POST FOREIGN KEY (FEED_POST_ID) REFERENCES FEED_POST (ID_FEED_POST) ON DELETE CASCADE,
    CONSTRAINT FK_FEED_POST_COMMENT_AUTHOR FOREIGN KEY (AUTHOR_USER_ID) REFERENCES USERS (ID_USER) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_LIKE_POST
    ON FEED_POST_LIKE (FEED_POST_ID);

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_COMMENT_POST_CREATED_AT
    ON FEED_POST_COMMENT (FEED_POST_ID, CREATED_AT);

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_COMMENT_AUTHOR
    ON FEED_POST_COMMENT (AUTHOR_USER_ID);
