ALTER TABLE USERS
    ADD COLUMN IF NOT EXISTS ROLE_LABEL VARCHAR(30) NOT NULL DEFAULT 'PROTETOR';

ALTER TABLE USERS
    DROP CONSTRAINT IF EXISTS CK_USERS_ROLE_LABEL;

ALTER TABLE USERS
    ADD CONSTRAINT CK_USERS_ROLE_LABEL CHECK (ROLE_LABEL IN ('ONG', 'PROTETOR'));

CREATE SEQUENCE IF NOT EXISTS SEQ_FEED_POST_VIDEO START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS FEED_POST_VIDEO (
    ID_FEED_POST_VIDEO BIGINT NOT NULL DEFAULT nextval('SEQ_FEED_POST_VIDEO'),
    FEED_POST_ID BIGINT NOT NULL,
    VIDEO_URL VARCHAR(500) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_FEED_POST_VIDEO PRIMARY KEY (ID_FEED_POST_VIDEO),
    CONSTRAINT FK_FEED_POST_VIDEO_POST FOREIGN KEY (FEED_POST_ID) REFERENCES FEED_POST (ID_FEED_POST) ON DELETE CASCADE,
    CONSTRAINT UK_FEED_POST_VIDEO_POST UNIQUE (FEED_POST_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FEED_POST_VIDEO_POST
    ON FEED_POST_VIDEO (FEED_POST_ID);
