ALTER TABLE FEED_POST DROP CONSTRAINT IF EXISTS FK_FEED_POST_ANIMAL;
ALTER TABLE FEED_POST DROP CONSTRAINT IF EXISTS CK_FEED_POST_TYPE;

DROP INDEX IF EXISTS IDX_FEED_POST_ANIMAL;

ALTER TABLE FEED_POST DROP COLUMN IF EXISTS ANIMAL_ID;
ALTER TABLE FEED_POST DROP COLUMN IF EXISTS POST_TYPE;
